### PR TITLE
Target for cloudwatch datasources.

### PR DESCRIPTION
**Pull request by liamstewart**
Opted for adding a `CloudWatchTarget` class rather than extending `Target` (or a new `BaseTarget` class) / removing attributes a-la https://github.com/weaveworks/grafanalib/pull/146.

### CODE REVIEW

**Comment by liamstewart** [comment]
Example use: strava/configuration#4682.

**Review by daveworth — APPROVED** [review]
Can we test it?  The tests in grafanalib could already use some love and the upstream team explicitly calls out that they are not religious about testing - only on critical functionality.  It would be cool if we could test the serialization though.

One thing that was interesting is I tried to get a cloudwatch datasource into the graphage playground this weekend and ran into weird security issues - it's worth trying again I think.  That's on me.

**Comment by liamstewart** [comment]
> Can we test it? The tests in grafanalib could already use some love and the upstream team explicitly calls out that they are not religious about testing - only on critical functionality. It would be cool if we could test the serialization though.

Will take a look.

> One thing that was interesting is I tried to get a cloudwatch datasource into the graphage playground this weekend and ran into weird security issues - it's worth trying again I think. That's on me.

Not quite sure that I understand. graphage playground? I'm using cloudwatch sources fine with the linked configuration PR which results in http://g.strava.com/d/Qato3EEik/laminar-rds?refresh=1m&orgId=1

**Comment by daveworth** [comment]
[Graphage Playground](https://github.com/strava/configuration/blob/master/mesos/tools/README.md#developing-a-dashboard-locally-against-production-data) is the new hotness to allow rapid local dashboard building/testing/etc but I struggled to get a CloudWatch source in there.  It is also now out of date w.r.t grafana versions and the migration to the 5 train blew up in my face - will work on that next

**Comment by liamstewart** [comment]
Tests added. They run locally with tox.

```
$ tox -e py36
GLOB sdist-make: /home/liam/work/strava/grafanalib/setup.py
...
grafanalib/tests/test_core.py ....                                                                                                                                                                           [ 13%]
grafanalib/tests/test_grafanalib.py ....                                                                                                                                                                     [ 27%]
grafanalib/tests/test_opentsdb.py .                                                                                                                                                                          [ 31%]
grafanalib/tests/test_validators.py ..................                                                                                                                                                       [ 93%]
grafanalib/tests/test_zabbix.py ..                                                                                                                                                                           [100%]
```

**Pull request merged**
