### PR TITLE
[INFRA-3137] change Tooltip valueType defult to INDIVIDUAL

### PR DESCRIPTION
**Pull request by jmilliron**
I guess after this is approved, I'll cut a new release and follow up with an update to the requirements file in configuration repo?

### CODE REVIEW

**Review by sabriel27 — APPROVED** [review]
I change the version in setup.py so it's a little easier to keep track of tags and whatnot: https://github.com/strava/grafanalib/blob/master/setup.py#L18 

I also add a note to the changelog: https://github.com/strava/grafanalib/blob/master/CHANGELOG.rst

Lots of :toil: for a single word change.

**Comment by jmilliron** [comment]
Updated those two files.  Once this is merged, do I just go into the GitHub release interface and cut a new release?  I see something about attaching files?

**Comment by sabriel27** [comment]
I haven't used the UI, so I don't know what these attached files are..... This is the flow I go through on the cli:

1. Merge into master
2. Pull master locally
3. `git tag -a "v5.x.x" -m <mesage>`
4. git push --tags

**Comment by jmilliron** [comment]
Perfect, thanks!

**Pull request merged**
