### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by Fluxx**
I was doing some dashboard work and I needed a new `TimeSeries.tooltipSort` constructor arg that was added to upstream grafanalib in https://github.com/weaveworks/grafanalib/commit/1a0a0e847df5fa9c9b8ca9a69f3d77028ac5133d.

I did my best to ensure any merge conflicts were fixed, largely by just picking the incoming code since it seems we haven't modified things too much. But let me know if that is a wrong approach to take.

### CODE REVIEW

**Comment by Fluxx** [comment]
@pauloconnor looks like you did this sync last time, so tagging you.

**Comment by pauloconnor** [comment]
Do we even need to maintain this fork any more?

**Comment by Fluxx** [comment]
I think we do, unfortunately. Weaveworks is [no more](https://thenewstack.io/end-of-an-era-weaveworks-closes-shop-amid-cloud-native-turbulence/), and while I am okay using whatever the latest version of the library was from them, we've modified our fork enough that we'll need to use it for the immediate future.

**Comment by pauloconnor** [comment]
Weaveworks is gone, but grafanalib is still being [updated](https://github.com/weaveworks/grafanalib/commits/main/). We haven't made _that_ many changes to our fork, mostly things that now exist in Grafana, and I know for a fact that part of our branch breaks with modern Grafana, specifically the table resource.

**Review by pauloconnor — APPROVED** [review]

**Comment by Fluxx** [comment]
Ah interesting. I'll add a todo for us to look at getting off the fork then. I had also noticed issues with our table type as well.

**Pull request merged**
